title = "100 Exercises to Learn Rust"
link = "https://rust-exercises.com/"
desc = "A course teaching the core concepts of Rust through a series of 100 interactive exercises, suitable for beginners with prior programming experience."
added = "2024-08-07"
accessed = "2024-08-07"
tags = ["course"]
