[_let_s_get_rusty__cheat_sheet]
title = ""Let's Get Rusty" Cheat Sheet"
link = "https://docs.google.com/document/d/1kQidzAlbqapu-WZTuw4Djik0uTqMZYyiMXTM9F21Dz4/edit"
desc = "An accessible guide introducing Rust's basic rules and types. Some familiarity with computer programming is expected."
added = "2024-07-08"
accessed = "2024-07-08"
tags = ["edu"]
