title = "A 5-Step Guide for Learning Embedded Rust"
link = "https://www.theembeddedrustacean.com/p/embedded-rust-learning-guide"
desc = "Start learning embedded Rust with this 5-step guide"
added = "2024-08-06"
accessed = "2024-08-06"
