title = "Aim For Immutability in Rust"
link = "https://corrode.dev/blog/immutability/"
desc = "Explains why variables are immutable in Rust by default."
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["variables", "rust-basics", "immutability"]
