title = "Alice Ryhl - What it takes to keep Tokio running"
link = "https://www.youtube.com/watch?v=Lc3aw_NIOt0"
desc = "A perspective on the often overlooked but crucial work required to sustain and improve open-source projects."
added = "2024-08-07"
accessed = "2024-08-07"
tags = ["video"]
