[annotate_code_for_a_reading_club]
title = "Annotate Code for a Reading Club"
link = "https://annotate.codereading.club/#/"
desc = "An online tool for sharing thoughts on source code with a code reading club."
added = "2024-07-08"
accessed = "2024-07-08"
tags = ["reading-club", "tool"]
