[begin_rust__a_complete_guide_to_programming_with_rust,_for_new_and_experienced_programmers_alike]
title = "Begin Rust: A complete guide to programming with Rust, for new and experienced programmers alike"
link = "https://www.amazon.com/Begin-Rust-programming-experienced-programmers/dp/B096LTR59F"
desc = ""
added = "2024-07-08"
accessed = "2024-07-08"
tags = ["book"]
