title = "Ben Wishovich - Full Stack Rust - Building Rust Websites with Leptos"
link = "https://www.youtube.com/watch?v=JJV5crU405s"
desc = " Come learn how to build a full stack Rust web app with Axum and Leptos, leveraging the power of Rust to deliver web apps rivalling any Javascript stack."
added = "2024-08-07"
accessed = "2024-08-07"
tags = ["video"]
