title = "cheats.rs - Idiomatic Rust tips"
link = "https://cheats.rs"
desc = "A list of quick tips to make your code more idiomatic."
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["idiomatic", "tips", "quick"]
