[code_like_a_pro_in_rust]
title = "Code Like a Pro in Rust"
link = "https://www.manning.com/books/code-like-a-pro-in-rust"
desc = "A fast-track guide to building and delivering professional quality software in Rust, covering essential Rust tooling, data structures, memory management, testing, asynchronous programming, and more."
added = "2024-08-06"
accessed = "2024-08-06"
tags = ["paid", "book"]