title = "Command-Line Rust"
link = "https://github.com/kyclark/command-line-rust"
desc = "Learn the language by writing Rust versions of common Unix coreutils."
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["coreutils", "learning", "unix"]
