[comprehensive rust]
title = "Comprehensive Rust"
link = "https://google.github.io/comprehensive-rust/"
desc = "A free Rust course from the Android team at Google designed to provide a comprehensive understanding of the language."
added = "2024-07-11"
accessed = "2024-07-11"
tags = ["edu", "course", "book"]