[computer_and_embedded_systems_engineering_at_tu_delft]
title = "Computer and Embedded Systems Engineering at TU Delft"
link = "https://cese.pages.ewi.tudelft.nl/"
desc = "TU Delft's computer and embedded systems engineering master home page"
added = "2024-08-07"
accessed = "2024-08-07"
tags = ["course"]