[comprehensive_rust]
title = "Comprehensive Rust"
link = "https://github.com/google/comprehensive-rust"
desc = "A four day Rust course developed by the Android team, covering all aspects of Rust."
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["course", "comprehensive", "learning"]