[comp6991__solving_modern_programming_problems_with_rust]
title = "COMP6991: Solving Modern Programming Problems with Rust"
link = "https://cgi.cse.unsw.edu.au/~cs6991/24T1/"
desc = "A graduate-level course that provides an in-depth exploration of Rust, covering its goals, features, and practical applications through lectures, workshops, exercises, and assignments."
added = "2024-07-12"
accessed = "2024-07-12"
tags = ["free", "course", "edu"]
