[concurrency programming via rust]
title = "Concurrency Programming via Rust"
link = "https://github.com/smallnest/concurrency-programming-via-rust"
desc = "Examples of concurrency concepts implemented in Rust,  as well as a CN textbook covering the material"
added = "2024-07-08"
accessed = "2024-07-08"
tags = ["edu", "concurrency", "cn", "code"]