title = "Creating a Rust function that returns a &str or String"
link = "https://hermanradtke.com/2015/05/29/creating-a-rust-function-that-returns-string-or-str.html"
desc = "How 'Into' and 'Cow' (Clone-on-write) work together to avoid allocations for string types."
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["string-handling", "functions"]
