title = "Diátaxis"
link = "https://diataxis.fr/"
desc = "A framework for organizing technical documentation to effectively meet the needs of users"
added = "2024-07-12"
accessed = "2024-07-12"
tags = ["todo", "docs"]
