[eecs_3_497__systems_programming_in_rust]
title = "EECS 3/497:  Systems Programming in Rust"
link = "https://users.cs.northwestern.edu/~jesse/course/eecs396rust-sp18/"
desc = "An overview of a university course on systems programming with Rust."
added = "2024-08-06"
accessed = "2024-08-06"
