[effective rust]
title = "Effective Rust"
link = "https://www.lurklurk.org/effective-rust/"
desc = "35 specific ways to improve your Rust code"
added = "2024-07-12"
accessed = "2024-07-12"
tags = ["free", "book"]