[effective_rust]
title = "Effective Rust"
link = "https://www.lurklurk.org/effective-rust/"
desc = "A collection of specific ways to improve your use of Rust"
added = "2024-08-06"
accessed = "2024-08-06"
