[elegant_library_apis_in_rust]
title = "Elegant Library APIs in Rust"
link = "https://deterministic.space/elegant-apis-in-rust.html"
desc = "Many helpful tips and tricks for writing libraries in Rust."
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["api-design", "libraries", "best-practices"]