title = "Embedded Rust Education: 2023 Reflections & 2024 Visions"
link = "https://blog.theembeddedrustacean.com/embedded-rust-education-2023-reflections-2024-visions"
desc = "A reflection on the author's journey in embedded Rust education over the past year, and hopes for the Rust embedded community in 2024."
added = "2024-08-06"
accessed = "2024-08-06"
