[ergonomic_apis_for_hard_problems]
title = "Ergonomic APIs for hard problems"
link = "https://www.youtube.com/watch?v=Phk0C-kLlho"
desc = "RustLab Conference, October 2022"
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["ergonomics", "rust-conference", "apis"]