[felienne_hermans__blog]
title = "Felienne Hermans' Blog"
link = "https://www.felienne.com/"
desc = "Vrije Universiteit Amsterdam's professor Felienne Herman studies Computer Science Education and blogs about her field here."
added = "2024-07-08"
accessed = "2024-07-08"
tags = ["edu"]
