title = "Ferrous Systems Teaching Material"
link = "https://ferrous-systems.github.io/teaching-material/index.html"
desc = "Free workshop material produced by Ferrous Systems for trainings."
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["material", "training"]
