title = "From Unsafe to Safe | Comprehensive Understanding of Unsafe Rust"
link = "https://alexzhang-5109.xlog.app/From-Unsafe-To-Safe--Comprehensive-Understanding-of-Unsafe-Rust"
desc = "A thorough explanation of Unsafe Rust, its necessity, and how to use it safely by maintaining safety and validity invariants."
added = "2024-08-06"
accessed = "2024-08-06"
tags = ["blog"]
