title = "Henk Oordt- Oxidizing Education"
link = "https://www.youtube.com/watch?v=KwZM0lSTvyk"
desc = "Henk Oordt discusses how to break the cycle of companies needing Rust developers and developers needing Rust jobs by enabling universities to start teaching Rust."
added = "2024-08-07"
accessed = "2024-08-07"
tags = ["video"]
