[high_assurance_rust]
title = "High Assurance Rust"
link = "https://highassurance.rs/"
desc = "Developing secure and robust software, focusing on embedded-friendly data structures in Rust."
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["embedded", "security", "robustness"]