[high assurance rust]
title = "High Assurance Rust"
link = "https://highassurance.rs/"
desc = "Provides an introduction to building performant software that we can trust. (WIP)"
added = "2024-07-08"
accessed = "2024-07-08"
tags = ["book"]