[how-to_compile_rust_faster]
title = "How-to Compile Rust Faster"
link = "https://blog.rust.careers/post/compile_rust_faster/"
desc = "Several tips and techniques to optimize the compilation of Rust projects."
added = "2024-08-07"
accessed = "2024-08-07"
