title = "How to Learn Rust (course)"
link = "https://learning.accelerant.dev/how-to-learn-rust"
desc = "A 12 week guided tour through the Rust learning resources."
added = "2024-08-06"
accessed = "2024-08-06"
tags = ["paid"]
