title = "Idiomatic Rust - Writing Concise and Elegant Rust Code"
link = "https://www.youtube.com/watch?v=P2mooqNMxMs"
desc = "FOSDEM 2018"
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["fosdem"]
