[idiomatic_rust_libraries]
title = "Idiomatic Rust Libraries"
link = "https://www.youtube.com/watch?v=0zOg8_B71gE"
desc = "Rustfest Kiev"
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["rustfest", "rust-libraries"]