[intro_to_rust_lang]
title = "Intro to Rust Lang"
link = "https://rust-stuco.github.io/"
desc = "An overview of an introductory Rust programming language course offered in Spring 2024."
added = "2024-08-07"
accessed = "2024-08-07"
tags = ["course"]