title = "Learn Rust in One Video"
link = "https://youtu.be/ygL_xcavzQ4?si=bMRP-anawIkF3qes"
desc = "A 2.5 hour video introduction to Rust."
added = "2024-07-10"
accessed = "2024-07-10"
tags = ["video"]
