[learn_rust_in_a_month_of_lunches_formerly,_easy_rust]
title = "Learn Rust in a Month of Lunches (formerly, Easy Rust)"
link = "https://www.reddit.com/r/rust/comments/10hskmj/easy_rust_has_been_reborn_on_manning_as_learn/"
desc = "An announcement of the release of Learn Rust in a Month of Lunches, a book aimed at beginners that provides an easy and accessible introduction to the language."
added = "2024-07-12"
accessed = "2024-07-12"
tags = ["book", "paid"]
