[learning_rust_through_open_source_and_live_code_reviews]
title = "Learning Rust through open source and live code reviews"
link = "https://loige.co/learning-rust-through-open-source-and-live-code-reviews/"
desc = "Covers patterns like 'FromStr' and exposing a CLI and a library in one crate."
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["rust-patterns", "code-review", "open-source"]