title = "Learning Rust"
link = "https://gist.github.com/noxasaxon/7bf5ebf930e281529161e51cd221cf8a"
desc = "A list of learning resources covering getting started, improving skills, tools, community, and book/course recommendations"
added = "2024-07-12"
accessed = "2024-07-12"
tags = ["list", "edu"]
