title = "Local Async Executors and why They Should be the default"
link = "https://maciej.codes/2022-06-09-local-async.html"
desc = "Advocates for the use of local async executors in Rust as a simpler and more performant alternative to the default multi-threaded async programming approach."
added = "2024-08-06"
accessed = "2024-08-06"
