[macros_for_a_more_productive_rust]
title = "Macros for a More Productive Rust"
link = "https://www.youtube.com/watch?v=dZiWkbnaQe8"
desc = "RustConf 2020"
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["rustconf", "macros", "productivity"]