title = "Master hexagonal architecture in Rust"
link = "https://www.howtocodeit.com/articles/master-hexagonal-architecture-rust"
desc = "Everything you need to write flexible, future-proof Rust applications using hexagonal architecture."
added = "2024-08-07"
accessed = "2024-08-07"
