title = "Math with distances in Rust: safety and correctness across units"
link = "https://ferrisellis.com/content/rust-implementing-units-for-types/"
desc = "How to create a system to cleanly and safely do arithmetic with lengths."
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["type-system", "math", "safety"]
