title = "Mithun Hunsur - Ambient: A Rust and WebAssembly Runtime for Cross-Platform Multiplayer Games"
link = "https://www.youtube.com/watch?v=tSnKx2irwzE"
desc = "Discover the power of Rust in WebAssembly with Ambient: an open-source runtime for high-performance multiplayer games and 3D applications (using WebGPU)"
added = "2024-08-07"
accessed = "2024-08-07"
tags = ["video"]
