title = "Next.js and Rust: An Innovative Approach to Full-Stack Development"
link = "https://joshmo.hashnode.dev/nextjs-and-rust-an-innovative-approach-to-full-stack-development"
desc = "A detailed tutorial on building a full-stack web application using Next.js for the frontend and Rust with the Axum framework for the backend, including features like authentication  and password reset functionality"
added = "2024-07-12"
accessed = "2024-07-12"
tags = ["free", "tutorial", "blog"]
