[nine_rules_for_elegant_rust_library_apis]
title = "Nine Rules for Elegant Rust Library APIs"
link = "https://www.youtube.com/watch?v=6-8-9ZV-2WQ"
desc = "Seattle Rust Meetup, Sep. 2022"
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["elegance", "library-apis"]