title = "PingCAP talent plan"
link = "https://github.com/pingcap/talent-plan"
desc = "A series of training courses about writing distributed systems in Rust."
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["training", "course", "distributed-systems"]
