title = "Possible Rust"
link = "https://www.possiblerust.com/"
desc = "A blog for intermediate Rust programmers exploring real-world code and design patterns."
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["intermediate", "blog", "design-patterns"]
