[programming_rust_fast,_safe_systems_development]
title = "Programming Rust: Fast, Safe Systems Development"
link = "https://www.oreilly.com/library/view/programming-rust-2nd/9781492052586/"
desc = "A comprehensive Rust Programming Guide that covers most of Rust's features in detail."
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["comprehensive", "features", "guide"]