title = "Programming an ARM microcontroller in Rust at four different levels of abstraction"
link = "https://pramode.in/2018/02/20/programming-a-microcontroller-in-rust-at-four-levels-of-abstraction/"
desc = "Demonstrates how Rust helps to move from low-level embedded code to high-level abstractions."
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["microcontroller", "arm", "abstraction"]
