[r_rust_rust_tech_stack]
title = "r/rust: Rust tech stack"
link = "https://www.reddit.com/r/rust/comments/11znoe5/rust_tech_stack/"
desc = "A thread discussing popular crates for full-stack web development with Rust."
added = "2024-08-06"
accessed = "2024-08-06"
tags = ["webdev"]