title = "Ripgrep Code Review"
link = "https://blog.mbrt.dev/posts/ripgrep/"
desc = "An analysis of the popular 'ripgrep' tool's source code."
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["analysis", "ripgrep", "code-review"]
