title = "Rust Patterns: Enums Instead Of Booleans"
link = "http://blakesmith.me/2019/05/07/rust-patterns-enums-instead-of-booleans.html"
desc = "Discusses how using enums instead of booleans can express intent more clearly in Rust."
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["patterns", "booleans", "enums"]
