title = "Rust by Practice"
link = "https://practice.course.rs/why-exercise.html"
desc = "Practice Rust with challenging examples, exercises and projects."
added = "2024-07-08"
accessed = "2024-07-08"
tags = ["free", "book", "online"]
