title = "Rust-Edu's Workshop"
link = "https://rust-edu.org/workshop/"
desc = "Learn more about past & future workshops from Rust-Edu."
added = "2024-07-08"
accessed = "2024-07-08"
tags = ["rust-edu"]
