[rust_programming_full_course_2024]
title = "Rust Programming Full Course 2024"
link = "https://www.youtube.com/watch?v=rQ_J9WH6CGk&t=31s"
desc = "A 3-hour course that covers essential topics, from basic syntax and data types to more advanced concepts like ownership, borrowing, and collection types."
added = "2024-08-07"
accessed = "2024-08-07"
tags = ["video"]