[rust-cs]
title = "Rust-CS"
link = "https://github.com/AbdesamedBendjeddou/Rusty-CS"
desc = "A structured Computer Science curriculum consisting of high-quality, freely-available resources. Maintained by Abdesamed Bendjeddou."
added = "2024-07-08"
accessed = "2024-07-08"
tags = ["gen-cs", "edu"]
