[rust_book_summary]
title = "Rust Book Summary"
link = "https://psibi.in/rust-book-summary/"
desc = "A chapter-by-chapter summary of the Rust Book"
added = "2024-07-10"
accessed = "2024-07-10"
tags = ["book", "summary"]
