title = "Rust fact vs. fiction: 5 Insights from Google's Rust journey in 2022"
link = "https://opensource.googleblog.com/2023/06/rust-fact-vs-fiction-5-insights-from-googles-rust-journey-2022.html"
desc = "Wondering about Rust? We're addressing rumors and providing insight gained from years of early adoption of Rust here at Google."
added = "2024-08-06"
accessed = "2024-08-06"
