[rust_101]
title = "Rust 101"
link = "https://101-rs.tweede.golf/"
desc = "A Rust University course by tweede golf."
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["course", "university", "learning"]