title = "Rust-Edu Mission Statement"
link = "https://rust-edu.org/news/announcement/"
desc = "Learn about the inception of Rust-Edu in our own words."
added = "2024-07-08"
accessed = "2024-07-08"
tags = ["rust-edu"]
