title = "rust-lang/rustlings"
link = "https://github.com/rust-lang/rustlings"
desc = "Small exercises to get you used to reading and writing Rust code."
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["exercises", "learning", "beginner"]
