[rustic_bits]
title = "Rustic Bits"
link = "https://llogiq.github.io/2016/02/11/rustic.html"
desc = "Small things that make for rustic code."
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["code-quality", "best-practices"]