[schedule a rust-edu team meeting]
title = "Schedule a Rust-Edu Team Meeting"
link = "https://www.when2meet.com/?16093741-EjxZl"
desc = ""
added = "2024-07-08"
accessed = "2024-07-08"
tags = ["rust-edu"]