title = "Small Rust Tutorial for MLOps"
link = "https://nogibjj.github.io/rust-tutorial/learn_rust_tips.html"
desc = "A tutorial for learning the language in the MLOps context. Covers a range, from getting started to advanced concepts like distributed computing and serverless."
added = "2024-07-12"
accessed = "2024-07-12"
tags = ["advanced", "book"]
