[software_security_is_a_programming_languages_issue]
title = "Software Security is a Programming Languages Issue"
link = "http://www.pl-enthusiast.net/2018/08/13/security-programming-languages-issue/"
desc = "Software security must be addressed by all programmers, not just security experts."
added = "2024-08-06"
accessed = "2024-08-06"
