title = "Taking string arguments in Rust"
link = "http://xion.io/post/code/rust-string-args.html"
desc = "Discussing how to avoid subtle issues with string handling and when to use 'str' vs 'String'."
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["best-practices", "strings", "arguments"]
