[the absolute minimum every software developer absolutely, positively must know about unicode and character sets (no excuses!)]
title = "The Absolute Minimum Every Software Developer Absolutely, Positively Must Know About Unicode and Character Sets (No Excuses!)"
link = "https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/"
desc = "Comprehensive guide on character encodings and Unicode for software developers"
added = "2024-07-12"
accessed = "2024-07-12"
tags = ["unicode", "blog"]