[the_absolute_minimum_every_software_developer_absolutely,_positively_must_know_about_unicode_and_character_sets_no_excuses!]
title = "The Absolute Minimum Every Software Developer Absolutely, Positively Must Know About Unicode and Character Sets (No Excuses!)"
link = "https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/"
desc = "Comprehensive guide on character encodings and Unicode for software developers"
added = "2024-07-12"
accessed = "2024-07-12"
tags = ["unicode", "blog"]
