[the_little_book_of_rust_books]
title = "The Little Book of Rust Books"
link = "https://lborb.github.io/book/title-page.html"
desc = "An overview of various Rust books, including official, unofficial, and application-focused titles, to serve as a resource for Rust learners"
added = "2024-07-11"
accessed = "2024-07-11"
tags = ["book", "edu"]
