[the_rust_book_abridged_]
title = "The Rust Book (Abridged)"
link = "https://jasonwalton.ca/rust-book-abridged/"
desc = "A condensedd version of the official Rust programming book, focusing on the core concepts for experienced developers."
added = "2024-08-06"
accessed = "2024-08-06"
tags = ["book", "free"]