[the_unconference_toolbox]
title = "The Unconference Toolbox"
link = "https://devonzuegel.com/the-unconference-toolbox"
desc = "A primer on what an unconference is, along with tips and ideas for hosting and attending unconference sessions, including session formats, facilitation tactics, and common points of failure."
added = "2024-08-07"
accessed = "2024-08-07"
