title = "Threadiversal Travel"
link = "https://shellsharks.com/threadiversal-travel#title"
desc = "A guide for Lemmy, Kbin and general Reddit off-ramping"
added = "2024-08-06"
accessed = "2024-08-06"
