title = "Tim McNamara - 4 levels of error handling"
link = "https://www.youtube.com/watch?v=hQWZGOuDYTE"
desc = "An interactive step-by-step guide to understand error handling in Rust for both new and experienced programmers."
added = "2024-08-07"
accessed = "2024-08-07"
tags = ["video"]
