title = "Tricks of the Trait: Enabling Ergonomic Extractors"
link = "https://www.youtube.com/watch?v=7DOYtnCXucw"
desc = "Rust Nation UK, Feb. 2023"
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["extractors", "traits", "ergonomics"]
