[which_is_more_idiomatic_functional,_imperative_or_a_mix_]
title = "Which is more idiomatic? Functional, imperative or a mix?"
link = "https://users.rust-lang.org/t/which-is-more-idiomatic-functional-imperative-or-a-mix/11278"
desc = "A discussion on Rust's users forum about the idiomatic way to write Rust code: functional, imperative, or a mix of both."
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["functional", "imperative", "coding-style"]