[why_you_should_be_worried_about_the_future_of_c_c_in_embedded__a_case_for_rust]
title = "Why You Should Be Worried About the Future of C/C++ in Embedded: A Case for Rust"
link = "https://blog.theembeddedrustacean.com/why-you-should-be-worried-about-the-future-of-cc-in-embedded-a-case-for-rust"
desc = "A professional working in embedded systems shares their concerns about the future of C/C++ in this field and makes a case for adoping Rust as a safer, modern alternative."
added = "2024-07-11"
accessed = "2024-07-11"
tags = ["c++", "embedded", "blog"]
