title = "Wrapping errors in Rust"
link = "https://edgarluque.com/blog/wrapping-errors-in-rust"
desc = "Wrapping 'reqwest::Error' and a custom error type as an enum to make library usage easier."
added = "2024-08-09"
accessed = "2024-08-09"
tags = ["rust-tips", "programming", "error-handling"]
